"""FastAPI router endpoints for chat streaming."""

import json
import logging
from typing import Any, List, Optional
from fastapi import APIRouter
from fastapi.responses import StreamingResponse
from pydantic import BaseModel

from app.config import settings
from app.agent import compiled_graph

logger = logging.getLogger("BE.routers.chat_router")

router = APIRouter()


def safe_json_dumps(obj: Any) -> str:
    """Safely dump objects to JSON strings, handling LangChain messages and custom types."""
    def default_serializer(o):
        if hasattr(o, "content"):
            return getattr(o, "content")
        if hasattr(o, "dict") and callable(getattr(o, "dict")):
            return o.dict()
        if hasattr(o, "__dict__"):
            return o.__dict__
        return str(o)

    return json.dumps(obj, default=default_serializer)


def sanitize_tool_input(tool_input: Any) -> Any:
    """Sanitizes tool input by removing internal framework parameters (e.g. state, config, messages)."""
    if isinstance(tool_input, dict):
        cleaned = {}
        for k, v in tool_input.items():
            # Exclude internal injected state/config/messages parameters
            if k in ("state", "config", "store", "callbacks", "run_manager", "runtime", "messages"):
                continue
            if isinstance(v, dict):
                cleaned[k] = sanitize_tool_input(v)
            else:
                cleaned[k] = v
        return cleaned
    return tool_input


class Message(BaseModel):
    role: str  # "user" or "model"
    content: str


class ChatStreamRequest(BaseModel):
    messages: List[Message]
    model: Optional[str] = None
    config: Optional[dict] = None
    apiKey: Optional[str] = None
    groupId: Optional[int] = None


async def event_generator(messages: List[Message], group_id: Optional[int] = None):
    """Generator yielding Server-Sent Events (SSE) from the LangGraph agent."""
    from langchain_core.messages import HumanMessage, AIMessage

    # Translate frontend message structure to LangChain message structures
    formatted_messages = []
    for msg in messages:
        if msg.role == "user":
            formatted_messages.append(HumanMessage(content=msg.content))
        else:
            formatted_messages.append(AIMessage(content=msg.content))

    logger.info(f"Invoking compiled agent graph with {len(formatted_messages)} messages and group_id: {group_id}")

    try:
        # Stream events token-by-token using LangChain astream_events
        async for event in compiled_graph.astream_events(
            {"messages": formatted_messages},
            config={"configurable": {"group_id": group_id}},
            version="v2"
        ):
            kind = event.get("event")

            # Stream actual response tokens & tool call chunks generated by the LLM
            if kind == "on_chat_model_stream":
                # Only stream tokens from the actual agent node, not from guardrails/injection checks
                node = event.get("metadata", {}).get("langgraph_node")
                if node == "agent":
                    chunk = event["data"].get("chunk")
                    if chunk:
                        # 1. Stream tool call input chunks (name, args, id, index)
                        tool_chunks = getattr(chunk, "tool_call_chunks", None)
                        if tool_chunks:
                            for tc in tool_chunks:
                                tc_index = tc.get("index", 0) if isinstance(tc, dict) else getattr(tc, "index", 0)
                                tc_name = tc.get("name") if isinstance(tc, dict) else getattr(tc, "name", None)
                                tc_args = tc.get("args") if isinstance(tc, dict) else getattr(tc, "args", "")
                                tc_id = tc.get("id") if isinstance(tc, dict) else getattr(tc, "id", None)

                                payload = {
                                    "type": "tool_call_delta",
                                    "index": tc_index,
                                }
                                if tc_name:
                                    payload["name"] = tc_name
                                if tc_id:
                                    payload["id"] = tc_id
                                if tc_args:
                                    payload["args"] = tc_args

                                yield f"data: {safe_json_dumps(payload)}\n\n"

                        # 2. Stream standard response text content tokens
                        raw_content = getattr(chunk, "content", None)
                        extracted_text = ""
                        if isinstance(raw_content, str):
                            extracted_text = raw_content
                        elif isinstance(raw_content, list):
                            text_parts = []
                            for part in raw_content:
                                if isinstance(part, str):
                                    text_parts.append(part)
                                elif isinstance(part, dict):
                                    if part.get("type") == "text" and part.get("text"):
                                        text_parts.append(part["text"])
                                    elif "text" in part and isinstance(part["text"], str):
                                        text_parts.append(part["text"])
                                elif hasattr(part, "text") and getattr(part, "text"):
                                    text_parts.append(str(getattr(part, "text")))
                            extracted_text = "".join(text_parts)

                        if extracted_text:
                            # Provide 'text' key alongside 'content' for backward compatibility
                            yield f"data: {safe_json_dumps({'type': 'text_delta', 'text': extracted_text, 'content': extracted_text})}\n\n"

            # When tool execution starts (LLM finished emitting tool call inputs)
            elif kind == "on_tool_start":
                tool_name = event.get("name")
                tool_run_id = event.get("run_id")
                tool_input = event.get("data", {}).get("input")

                payload = {
                    "type": "tool_call_executing",
                    "name": tool_name,
                    "id": tool_run_id,
                    "input": sanitize_tool_input(tool_input),
                }
                yield f"data: {safe_json_dumps(payload)}\n\n"

            # When tool execution completes
            elif kind == "on_tool_end":
                tool_name = event.get("name")
                tool_run_id = event.get("run_id")
                # Intentionally DO NOT yield event["data"]["output"] to suppress raw tool payloads from stream
                payload = {
                    "type": "tool_call_end",
                    "name": tool_name,
                    "id": tool_run_id,
                    "status": "completed"
                }
                yield f"data: {safe_json_dumps(payload)}\n\n"

            # Yield fixed responses (like security warning blocks) on node end
            elif kind == "on_chain_end" and event.get("name") == "respond_unsafe":
                output = event.get("data", {}).get("output", {})
                messages = output.get("messages", [])
                for msg in messages:
                    content = getattr(msg, "content", None) or (msg if isinstance(msg, str) else "")
                    if content:
                        yield f"data: {safe_json_dumps({'type': 'text_delta', 'text': content, 'content': content})}\n\n"


        # SSE completion signal
        yield "data: [DONE]\n\n"
        logger.info("Agent response stream completed successfully.")

    except Exception as e:
        logger.error(f"Error during agent execution stream: {e}")
        yield f"data: {safe_json_dumps({'type': 'error', 'error': str(e)})}\n\n"



@router.post("/api/chat/stream")
async def chat_stream(req: ChatStreamRequest):
    """Exposes Server-Sent Events (SSE) streaming chat completions from the agent."""
    logger.info(f"Received stream request. Model: {req.model or settings.llm_model}, Group ID: {req.groupId}")
    return StreamingResponse(
        event_generator(req.messages, group_id=req.groupId),
        media_type="text/event-stream"
    )
