"""FastAPI router endpoints for chat streaming."""

import json
import logging
from typing import List, Optional
from fastapi import APIRouter
from fastapi.responses import StreamingResponse
from pydantic import BaseModel

from app.config import settings
from app.agent import compiled_graph

logger = logging.getLogger("BE.routers.chat_router")

router = APIRouter()


class Message(BaseModel):
    role: str  # "user" or "model"
    content: str


class ChatStreamRequest(BaseModel):
    messages: List[Message]
    model: Optional[str] = None
    config: Optional[dict] = None
    apiKey: Optional[str] = None


async def event_generator(messages: List[Message]):
    """Generator yielding Server-Sent Events (SSE) from the LangGraph agent."""
    from langchain_core.messages import HumanMessage, AIMessage
    
    # Translate frontend message structure to LangChain message structures
    formatted_messages = []
    for msg in messages:
        if msg.role == "user":
            formatted_messages.append(HumanMessage(content=msg.content))
        else:
            formatted_messages.append(AIMessage(content=msg.content))

    logger.info(f"Invoking compiled agent graph with {len(formatted_messages)} messages.")
    
    try:
        # Stream events token-by-token using LangChain astream_events
        async for event in compiled_graph.astream_events({"messages": formatted_messages}, version="v2"):
            kind = event.get("event")
            
            # Stream status update when agent calls the Neo4j RAG tool
            if kind == "on_tool_start":
                tool_name = event.get("name")
                tool_input = event.get("data", {}).get("input")
                # Format a status block in markdown
                status_msg = f"\n\n*> Agent Status: Querying Neo4j Graph Database for '{tool_input}'...*\n\n"
                yield f"data: {json.dumps({'text': status_msg})}\n\n"
                
            # Stream actual response tokens generated by the LLM
            elif kind == "on_chat_model_stream":
                # Only stream tokens from the actual agent node, not from guardrails/injection checks
                node = event.get("metadata", {}).get("langgraph_node")
                if node == "agent":
                    chunk = event["data"].get("chunk")
                    if chunk and hasattr(chunk, "content") and chunk.content:
                        yield f"data: {json.dumps({'text': chunk.content})}\n\n"
                    
            # Yield fixed responses (like security warning blocks) on node end
            elif kind == "on_chain_end" and event.get("name") == "respond_unsafe":
                output = event.get("data", {}).get("output", {})
                messages = output.get("messages", [])
                for msg in messages:
                    content = getattr(msg, "content", None) or (msg if isinstance(msg, str) else "")
                    if content:
                        yield f"data: {json.dumps({'text': content})}\n\n"

                    
        # SSE completion signal
        yield "data: [DONE]\n\n"
        logger.info("Agent response stream completed successfully.")
        
    except Exception as e:
        logger.error(f"Error during agent execution stream: {e}")
        yield f"data: {json.dumps({'error': str(e)})}\n\n"


@router.post("/api/chat/stream")
async def chat_stream(req: ChatStreamRequest):
    """Exposes Server-Sent Events (SSE) streaming chat completions from the agent."""
    logger.info(f"Received stream request. Model: {req.model or settings.llm_model}")
    return StreamingResponse(
        event_generator(req.messages),
        media_type="text/event-stream"
    )
