"""Add document groups

Revision ID: e0395f031cb8
Revises: 3622b56d487f
Create Date: 2026-07-17 23:01:22.769920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0395f031cb8'
down_revision: Union[str, Sequence[str], None] = '3622b56d487f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_document_groups_id'), 'document_groups', ['id'], unique=False)
    op.add_column('documents', sa.Column('group_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'documents', 'document_groups', ['group_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_column('documents', 'group_id')
    op.drop_index(op.f('ix_document_groups_id'), table_name='document_groups')
    op.drop_table('document_groups')
    # ### end Alembic commands ###
