"""FastAPI Server exposing SSE streaming Chat API integrated with Graph RAG Agent."""

import json
import logging
import sys
import os
from typing import Any, Dict, List, Optional
import uvicorn
import asyncio
from fastapi import FastAPI, Request, UploadFile, File, BackgroundTasks
from fastapi.responses import StreamingResponse
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel

# Add path configurations for local imports
sys.path.insert(0, os.path.dirname(__file__))

from config import settings
from agent import deep_agent, graph_indexing_service
from storage import init_storage, save_document_metadata, update_document_status, upload_file_to_minio, get_file_from_minio, list_documents
from parser import extract_text

# Configure logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("BE.main")

app = FastAPI(title="Graph RAG Backend", version="1.0.0")

@app.on_event("startup")
def startup_event():
    logger.info("Initializing database tables and storage buckets...")
    init_storage()

# Enable CORS for frontend integration
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# ── Pydantic Request Models ──────────────────────────────────────────────────

class Message(BaseModel):
    role: str  # "user" or "model"
    content: str


class ChatStreamRequest(BaseModel):
    messages: List[Message]
    model: Optional[str] = None
    config: Optional[dict] = None
    apiKey: Optional[str] = None


class VerifyKeyRequest(BaseModel):
    apiKey: Optional[str] = None


# ── API Endpoints ────────────────────────────────────────────────────────────

@app.get("/api/config")
async def get_config():
    """Endpoint checked by FE to verify environment configuration status."""
    logger.info("Config status checked.")
    return {
        "hasSystemKey": True  # Since keys are preconfigured in config.yaml
    }


@app.post("/api/verify-key")
async def verify_key(req: VerifyKeyRequest):
    """Endpoint checked by FE settings to verify API key or server status."""
    logger.info("Verifying configuration and database connectivity...")
    try:
        # Check settings validation
        settings.validate()
        return {"valid": True, "message": "Server configuration is valid and active!"}
    except Exception as e:
        logger.error(f"Validation failed: {e}")
        return {"valid": False, "message": f"Configuration error: {str(e)}"}


async def event_generator(messages: List[Message]):
    """Generator yielding Server-Sent Events (SSE) from the LangGraph agent."""
    from langchain_core.messages import HumanMessage, AIMessage
    
    # Translate frontend message structure to LangChain message structures
    formatted_messages = []
    for msg in messages:
        if msg.role == "user":
            formatted_messages.append(HumanMessage(content=msg.content))
        else:
            formatted_messages.append(AIMessage(content=msg.content))

    logger.info(f"Invoking deep agent with {len(formatted_messages)} messages.")
    
    try:
        # Stream events token-by-token using LangChain astream_events
        async for event in deep_agent.astream_events({"messages": formatted_messages}, version="v2"):
            kind = event.get("event")
            
            # Stream status update when agent calls the Neo4j RAG tool
            if kind == "on_tool_start":
                tool_name = event.get("name")
                tool_input = event.get("data", {}).get("input")
                # Format a status block in markdown
                status_msg = f"\n\n*> Agent Status: Querying Neo4j Graph Database for '{tool_input}'...*\n\n"
                yield f"data: {json.dumps({'text': status_msg})}\n\n"
                
            # Stream actual response tokens generated by the LLM
            elif kind == "on_chat_model_stream":
                chunk = event["data"].get("chunk")
                if chunk and hasattr(chunk, "content") and chunk.content:
                    yield f"data: {json.dumps({'text': chunk.content})}\n\n"
                    
        # SSE completion signal
        yield "data: [DONE]\n\n"
        logger.info("Agent response stream completed successfully.")
        
    except Exception as e:
        logger.error(f"Error during agent execution stream: {e}")
        yield f"data: {json.dumps({'error': str(e)})}\n\n"


@app.post("/api/chat/stream")
async def chat_stream(req: ChatStreamRequest):
    """Exposes Server-Sent Events (SSE) streaming chat completions from the agent."""
    logger.info(f"Received stream request. Model: {req.model or settings.llm_model}")
    return StreamingResponse(
        event_generator(req.messages),
        media_type="text/event-stream"
    )


@app.get("/api/documents")
async def get_documents():
    """Returns list of uploaded documents and indexing metadata from Postgres."""
    logger.info("Listing documents...")
    try:
        return list_documents()
    except Exception as e:
        logger.error(f"Failed to list documents: {e}")
        return []


async def index_document_background(doc_id: int, minio_key: str, filename: str):
    """Asynchronous background task to extract text, run RAG indexing, and update database."""
    try:
        # 1. Update status to processing
        update_document_status(doc_id, "processing")
        
        # 2. Fetch content from MinIO
        file_bytes = get_file_from_minio(minio_key)
        
        # 3. Extract text content
        text = extract_text(filename, file_bytes)
        
        # 4. Ingest text into Graph RAG
        logger.info(f"Indexing document {doc_id} ('{filename}') via GraphIndexingService...")
        loop = asyncio.get_running_loop()
        res = await loop.run_in_executor(None, graph_indexing_service.index_text, text)
        
        # 5. Extract statistics
        entities = res.get("entities", [])
        relations = res.get("relationships", [])
        
        update_document_status(
            doc_id, 
            "indexed", 
            entity_count=len(entities), 
            relationship_count=len(relations)
        )
        logger.info(f"Document {doc_id} ('{filename}') indexed successfully. Entities: {len(entities)}, Relations: {len(relations)}")
    except Exception as e:
        logger.error(f"Failed to index document {doc_id} ('{filename}'): {e}")
        update_document_status(doc_id, "failed")


@app.post("/api/documents/upload")
async def upload_document(background_tasks: BackgroundTasks, file: UploadFile = File(...)):
    """Uploads document to MinIO, saves metadata to Postgres, and schedules background RAG indexing."""
    filename = file.filename
    logger.info(f"Received file upload request: {filename}")
    try:
        # Read file bytes
        file_bytes = await file.read()
        
        # 1. Upload to MinIO
        minio_key = upload_file_to_minio(file_bytes, filename)
        
        # 2. Create document record in Postgres (status="pending")
        doc_metadata = save_document_metadata(filename, minio_key)
        
        # 3. Enqueue background indexing task
        background_tasks.add_task(
            index_document_background, 
            doc_metadata["id"], 
            minio_key, 
            filename
        )
        
        return {
            "status": "success",
            "message": "File uploaded successfully. Indexing started in background.",
            "document": doc_metadata
        }
    except Exception as e:
        logger.error(f"Upload failed for '{filename}': {e}")
        return {
            "status": "error",
            "message": f"Failed to upload document: {str(e)}"
        }


# ── Server Boot ──────────────────────────────────────────────────────────────

if __name__ == "__main__":
    logger.info(f"Starting FastAPI server on {settings.server_host}:{settings.server_port}")
    uvicorn.run(
        "main:app",
        host=settings.server_host,
        port=settings.server_port,
        reload=True
    )
